inherit_from: .rubocop_config.yml
AllCops:
  TargetRubyVersion: 2.5.1

Metrics/AbcSize:
  Max: 23

# Offense count: 2
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 33

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 22

# Offense count: 4
Style/ClassVars:
  Exclude:
    - 'lib/cloud_party/config.rb'
    - 'lib/cloud_party/simple.rb'

# Offense count: 23
Style/Documentation:
  Enabled: false

# Offense count: 12
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 110
